### ISSUE TITLE
Creacion de clase respuesta

### ISSUE THREAD

**Issue by StefDeVita** [fvazquezf/TP_2_Algo_3#20]
Creacion de una clase respuesta para reemplazar los booleanos utilizados, utilizando un diccionario con clave numero de respuesta y valor true/false dependiendo de si es correcta o no,checkeando que funcione con pregunta verdadero/falso clasica.

**Comment by rulochaparro** [comment]
Se realiza el feature con las pruebas pasnado correctamente. Se procede a cerrar el issue
