### ISSUE TITLE
Implementacion de verdadero/falso con penalidad

### ISSUE THREAD

**Issue by StefDeVita** [fvazquezf/TP_2_Algo_3#21]
Creacion de pruebas y codigo que haga que pasen para las preguntas de tipo verdadero/falso con penalidad. Teniendo en cuenta que se debera refactorizar el conteo de puntos creando un objeto que se encargue de ello.

**Comment by rulochaparro** [comment]
Estuvimos trabajando con @fvazquezf para la creación de las distitnas preguntas (enfocandonos en Pregunta Vo F clásica o con penalidad).Estamos debatiendo la mejor forma de encarar esto. Si utilizando una clase abstracta o concreta "Pregunta" y de ahí implmentar/heredar las distitnas preguntas, utilizar métodos de clase para la creación de cada pregunta. ¿Vale la pena utilizar el patrón factory? Esto se replicaría para la clase respuesta y para la clase calculador de puntos.
